name: Run tests in cookbook

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - '*'

jobs:
  tests_in_cookbook:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
    - name: Checkout Test Repository
      uses: actions/checkout@v4
      with:
        repository: 'rzyu45/Solverz-Cookbook'
        ref: 'main'

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        python-version: ${{ matrix.python-version }}


    - name: Install Main Repository as Dependency using Git URL
      run: |
        uv venv 
        uv pip install git+https://github.com/${{github.repository}}.git@${{ github.sha }}
        uv pip install pytest pytest-xdist pytest-datadir

    - name: Run Tests
      run: |
        uv run pytest -n auto
