name: Run tests in cookbook

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - '*'

jobs:
  tests_in_cookbook:

    runs-on: windows-latest

    steps:
    - name: Checkout Test Repository
      uses: actions/checkout@v4
      with:
        repository: 'rzyu45/Solverz-Cookbook'
        ref: 'main'

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Main Repository as Dependency using Git URL
      run: |
        uv venv 
        uv pip install git+https://github.com/${{github.repository}}.git@${{ github.sha }}
        uv pip install pytest-xdist

    - name: Run Tests
      run: |
        uv run pytest -n auto
