name: Run tests in SolMuseum

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - '*'

jobs:
  tests_in_museum:

    runs-on: windows-latest

    steps:
    - name: Checkout Test Repository
      uses: actions/checkout@v3
      with:
        repository: 'smallbunnies/SolMuseum'
        ref: 'main'
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # caching pip dependencies

    - name: Install Main Repository as Dependency using Git URL
      run: |
        pip install --upgrade pip setuptools wheel
        pip install git+https://github.com/${{github.repository}}.git@${{ github.sha }}
        pip install git+https://github.com/rzyu45/SolUtil@master
        pip install pytest-xdist

    - name: Run Tests
      run: |
        pytest -n auto
